---
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
    recursive: yes
  become: false

- name: Link dotfiles into home folder by calling install script
  command:
    cmd: "./install.sh"
  become: false
  args:
    chdir: "{{ dotfiles_repo_local_destination }}"
  changed_when: False
